language: php

matrix:
  include:
    - php: 7.1
      env: CODE_ANALYSIS=true
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: MONOREPO_SPLIT=true STANDALONE=true
    - php: 7.3
  # for better contributor experience
  allow_failures:
    - php: 7.1
      env: CODE_ANALYSIS=true

before_script:
  - composer update --prefer-dist --no-progress --no-suggest --ansi

script:
  - vendor/bin/phpunit
  - |
    if [[ $CODE_ANALYSIS == true ]]; then
        composer check-all
    fi

  - |
    if [[ $STANDALONE == true ]]; then
        for DIRECTORY in `find packages -mindepth 1 -maxdepth 1 -type d`
        do
            CMD="vendor/bin/phpunit $DIRECTORY"
            echo "Running '$CMD'"
            $CMD
        done
    fi

after_script:
  - |
    if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" && $MONOREPO_SPLIT == true ]]; then
        composer split
    fi

notifications:
  email: false
