services:
    _defaults:
        autowire: true
        autoconfigure: true

    EonX\EasySecurity\Bridge\Symfony\Resolvers\DecoratorContextResolver: ~

    EonX\EasySecurity\Bridge\Symfony\Security\ContextAuthenticator:
        arguments:
            $contextResolver: '@EonX\EasySecurity\Bridge\Symfony\Resolvers\DecoratorContextResolver'

    EonX\EasySecurity\Interfaces\Resolvers\ContextResolverInterface:
        class: EonX\EasySecurity\Resolvers\ContextResolver

    EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredContextResolverInterface:
        class: EonX\EasySecurity\Bridge\Symfony\Helpers\DeferredContextResolver
