services:
    _defaults:
        autowire: true
        autoconfigure: true

    EonX\EasySecurity\Bridge\Symfony\Security\ContextAuthenticator: ~

    EonX\EasySecurity\Bridge\Symfony\Interfaces\AuthenticationFailureResponseFactoryInterface:
        class: EonX\EasySecurity\Bridge\Symfony\Factories\AuthenticationFailureResponseFactory

    EonX\EasySecurity\Interfaces\SecurityContextFactoryInterface:
        class: EonX\EasySecurity\SecurityContextFactory

    EonX\EasySecurity\Interfaces\SecurityContextResolverInterface:
        class: EonX\EasySecurity\SecurityContextResolver

    EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredSecurityContextResolverInterface:
        class: EonX\EasySecurity\Bridge\Symfony\Helpers\DeferredSecurityContextResolver

    EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredContextResolverInterface: '@EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredSecurityContextResolverInterface'
