services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Authorization
    EonX\EasySecurity\Interfaces\Authorization\AuthorizationMatrixFactoryInterface:
        class: EonX\EasySecurity\Authorization\AuthorizationMatrixFactory

    EonX\EasySecurity\Interfaces\Authorization\AuthorizationMatrixInterface:
        factory: ['@EonX\EasySecurity\Interfaces\Authorization\AuthorizationMatrixFactoryInterface', 'create']

    EonX\EasySecurity\Bridge\Symfony\Security\ContextAuthenticator: null

    EonX\EasySecurity\Bridge\Symfony\Interfaces\AuthenticationFailureResponseFactoryInterface:
        class: EonX\EasySecurity\Bridge\Symfony\Factories\AuthenticationFailureResponseFactory

    EonX\EasySecurity\Interfaces\SecurityContextFactoryInterface:
        class: EonX\EasySecurity\SecurityContextFactory

    EonX\EasySecurity\Interfaces\SecurityContextResolverInterface:
        class: EonX\EasySecurity\SecurityContextResolver

    EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredSecurityContextResolverInterface:
        class: EonX\EasySecurity\Bridge\Symfony\Helpers\DeferredSecurityContextResolver

    EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredContextResolverInterface: '@EonX\EasySecurity\Bridge\Symfony\Interfaces\DeferredSecurityContextResolverInterface'

    # Voters
    EonX\EasySecurity\Bridge\Symfony\Security\Voters\PermissionVoter: null
    EonX\EasySecurity\Bridge\Symfony\Security\Voters\RoleVoter: null
