services:
    _defaults:
        autoconfigure: true
        autowire: true

    EonX\EasySsm\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel/*'
            - '../src/Services/Aws/Data/*'
            - '../src/Services/Dotenv/Data/*'
            - '../src/Services/Dotenv/Loaders/*'
            - '../src/Services/Parameters/Data/*'

    # Factories
    EonX\EasySsm\Helpers\Arr:
        factory: ['@EonX\EasySsm\Factories\ArrFactory', 'create']

    Symfony\Component\Filesystem\Filesystem:
        factory: ['@EonX\EasySsm\Factories\FilesystemFactory', 'create']

    EonX\EasySsm\Helpers\Parameters:
        factory: ['@EonX\EasySsm\Factories\ParametersHelperFactory', 'create']

    Aws\Ssm\SsmClient:
        factory: ['@EonX\EasySsm\Factories\SsmClientFactory', 'create']

    EonX\EasySsm\Services\Dotenv\SsmDotenvInterface:
        class: EonX\EasySsm\Services\Dotenv\SsmDotenv
        public: true

    Symfony\Component\Console\Output\OutputInterface:
        class: Symfony\Component\Console\Output\ConsoleOutput

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
