name: PHP-CI
on: [push]
jobs:
    composer:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   if: steps.cache-composer.outputs.cache-hit == false
                name: Install dependencies
                run: composer global require hirak/prestissimo; composer install --prefer-dist --no-progress --no-suggest;

            -   if: steps.cache-composer.outputs.cache-hit == false
                uses: eonx-com/actions-upload-artifact@v1
                with:
                    name: ${{ matrix.php }}-composer-lock
                    path: composer.lock

    ecs:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check ECS
                run: composer check-ecs

    phpstan:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check PHPStan
                run: composer check-phpstan

    security:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   uses: eonx-com/actions-download-artifact@v1
                with:
                    name: ${{ matrix.php }}-composer-lock

            -   name: Move composer.lock
                run: |
                    cp ${{ matrix.php }}-composer-lock/composer.lock ./composer.lock; \
                    rm -rf ${{ matrix.php }}-composer-lock;

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check Security
                run: composer check-security

    tests:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check Tests
                run: composer check-tests
