name: PHP-CI
on: [push]
jobs:
    coding_standards:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.2', '7.3', '7.4' ]
                script:
                    - { name: Check ECS, script: composer check-ecs }
                    - { name: Check PHPStan, script: composer check-phpstan }
                    - { name: Check Security, script: composer check-security }
                    - { name: Check Tests, script: composer check-tests }

        name: ${{ matrix.script.name }}

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php }}-comp-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ matrix.php }}-comp-

            -   run: composer global require hirak/prestissimo; composer install --prefer-dist --no-progress;

            -   name: '[CI] Check ${{ matrix.script }} [CI]'
                run: ${{ matrix.script.script }}

    monorepo:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php }}-comp-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ matrix.php }}-comp-

            -   run: composer global require hirak/prestissimo; composer install --prefer-dist --no-progress;

            -   name: '[CI] Check composer [CI]'
                run: composer validate --strict

            -   name: '[CI] Check monorepo [CI]'
                run: composer validate-repo
