name: PHP-CI
on: [push]
jobs:
    composer:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: eonx-com/actions-cache@v1
                id: composer-cache
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: composer-${{ matrix.php }}-

            -   if: steps.composer-cache.outputs.cache-hit == false
                run: |
                    composer global require hirak/prestissimo; \
                    composer install --prefer-dist --no-progress; \
                    mkdir cache; \
                    cp ./composer.lock ./cache/composer.lock;

            -   if: steps.composer-cache.outputs.cache-hit == false
                uses: eonx-com/actions-cache@v1
                with:
                    path: cache
                    key: composer-lock-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: composer-lock-${{ matrix.php }}-

    ecs:
        runs-on: ubuntu-latest
        needs: composer
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: composer-${{ matrix.php }}-

            -   name: '[CI] Check ECS [CI]'
                run: composer check-ecs

    phpstan:
        runs-on: ubuntu-latest
        needs: composer
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: composer-${{ matrix.php }}-

            -   name: '[CI] Check PHPStan [CI]'
                run: composer check-phpstan

    security:
        runs-on: ubuntu-latest
        needs: composer
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: cache
                    key: composer-lock-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: composer-lock-${{ matrix.php }}-

            -   run: |
                    cp ./cache/composer.lock ./composer.lock; \
                    rm -rf cache;

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: composer-${{ matrix.php }}-

            -   name: '[CI] Check Security [CI]'
                run: composer check-security

    tests:
        runs-on: ubuntu-latest
        needs: composer
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: composer-${{ matrix.php }}-

            -   name: '[CI] Check Tests [CI]'
                run: composer check-tests
