name: PHP-CI
on: [push]
jobs:
    composer:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   if: steps.cache-composer.outputs.cache-hit == false
                name: Install dependencies
                run: |
                    composer global require hirak/prestissimo; composer install --prefer-dist --no-progress --no-suggest; \
                    mkdir cache; \
                    cp ./composer.lock ./cache/composer.lock;

            -   if: steps.cache-composer.outputs.cache-hit == false
                uses: eonx-com/actions-cache@v1
                with:
                    path: cache
                    key: composer-lock-${{ matrix.php }}

    ecs:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check ECS
                run: composer check-ecs

    phpstan:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check PHPStan
                run: composer check-phpstan

    security:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: cache
                    key: composer-lock-${{ matrix.php }}

            -   name: Move composer.lock
                run: |
                    cp cache/composer.lock ./composer.lock; \
                    rm -rf cache;

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check Security
                run: composer check-security

    tests:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: vendor
                    key: composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

            -   name: Check Tests
                run: composer check-tests
