name: PHP-CI

on: [push, pull_request]

jobs:
    # 2nd run with cache + parallel
    coding_standards:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '7.3' ]
                actions:
                    - { name: ecs, coverage: none, run: composer check-ecs }
                    # @validate-repo was removed from composer.json until monorepo-builder is fixed
                    - { name: monorepo, coverage: none, run: composer check-monorepo }
                    - { name: phpstan, coverage: none, run: composer check-phpstan }
                    - { name: security, coverage: none, run: composer check-security }
                    -   name: tests
                        coverage: pcov
                        run: |
                            composer check-tests | tee coverage_output.txt
                            packages/EasyTest/bin/easy-test check-coverage -c 70 coverage_output.txt

        name: ${{ matrix.actions.name}} (${{ matrix.php }})

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: ${{ matrix.actions.coverage }}

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php }}-comp-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ matrix.php }}-comp-

            -   run: composer global require hirak/prestissimo
            -   run: composer install --prefer-dist --no-progress

            -   name: '[CI] Check ${{ matrix.actions.name }} [CI]'
                run: ${{ matrix.actions.run }}
                shell: bash
