name: PHP-CI
on: [push]
jobs:
    composer:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.2', '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   name: Install dependencies
                run: composer global require hirak/prestissimo; composer install --prefer-dist --no-progress --no-suggest;

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ github.ref }}-${{ matrix.php }}-${{ hashFiles('composer.lock') }}

            -   uses: eonx-com/actions-upload-artifact@v1
                with:
                    name: ${{ github.ref }}-${{ matrix.php }}-composer-lock
                    path: composer.lock

    ecs:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.2', '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   uses: eonx-com/actions-download-artifact@v1
                with:
                    name: ${{ github.ref }}-${{ matrix.php }}-composer-lock

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ github.ref }}-${{ matrix.php }}-${{ hashFiles('composer.lock') }}

            -   name: Check ECS
                run: composer check-ecs

    phpstan:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.2', '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   uses: eonx-com/actions-download-artifact@v1
                with:
                    name: ${{ github.ref }}-${{ matrix.php }}-composer-lock

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ github.ref }}-${{ matrix.php }}-${{ hashFiles('composer.lock') }}

            -   name: Check PHPStan
                run: composer check-phpstan

    security:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.2', '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   uses: eonx-com/actions-download-artifact@v1
                with:
                    name: ${{ github.ref }}-${{ matrix.php }}-composer-lock

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ github.ref }}-${{ matrix.php }}-${{ hashFiles('composer.lock') }}

            -   name: Check Security
                run: composer check-security

    tests:
        needs: composer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.2', '7.3' ]
        steps:
            -   uses: eonx-com/checkout@v2

            -   uses: eonx-com/actions-download-artifact@v1
                with:
                    name: ${{ github.ref }}-${{ matrix.php }}-composer-lock

            -   name: Cache Composer dependencies
                id: cache-composer
                uses: eonx-com/cache@v1
                with:
                    path: vendor
                    key: composer-${{ github.ref }}-${{ matrix.php }}-${{ hashFiles('composer.lock') }}

            -   name: Check Tests
                run: composer check-tests
