name: PHP-CI
on: [push]
jobs:
    coding_standards:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
                actions:
                    - { name: ECS, run: composer check-ecs }
                    - { name: PHPStan, run: composer check-phpstan }
                    - { name: Security, run: composer check-security }
                    - { name: Tests, run: composer check-tests }
                    - { name: Monorepo, run: composer check-monorepo }

        name: ${{ matrix.actions.name }} (${{ matrix.php }})

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php }}-comp-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ matrix.php }}-comp-

            -   run: composer global require hirak/prestissimo
            -   run: composer install --prefer-dist --no-progress

            -   name: '[CI] Check ${{ matrix.actions.name }} [CI]'
                run: ${{ matrix.actions.run }}
