name: PHP-CI
on: [push]
jobs:
    ecs:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache-dir
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache-dir.outputs.dir }}
                    key: comp-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: comp-${{ matrix.php }}-

            -   name: '[CI] Check ECS [CI]'
                run: |
                    composer global require hirak/prestissimo; \
                    composer install --prefer-dist; \
                    composer check-ecs

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache-dir
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache-dir.outputs.dir }}
                    key: comp-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: comp-${{ matrix.php }}-

            -   name: '[CI] Check PHPStan [CI]'
                run: |
                    composer global require hirak/prestissimo; \
                    composer install --prefer-dist; \
                    composer check-phpstan

    security:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache-dir
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache-dir.outputs.dir }}
                    key: comp-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: comp-${{ matrix.php }}-

            -   name: '[CI] Check Security [CI]'
                run: |
                    composer global require hirak/prestissimo; \
                    composer install --prefer-dist; \
                    composer check-security

    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache-dir
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache-dir.outputs.dir }}
                    key: comp-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
                    restore-keys: comp-${{ matrix.php }}-

            -   name: '[CI] Check Tests [CI]'
                run: |
                    composer global require hirak/prestissimo; \
                    composer install --prefer-dist; \
                    composer check-tests
