name: PHP Versions

on: [push]

jobs:
    php_versions_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '7.1', '7.2', '7.3' ]

        name: Tests For PHP${{ matrix.php }}

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: composer install --prefer-dist --no-progress

            -   run: composer check-tests
