name: Split Packages

on:
    push:
        branches:
            - feature/git-subtree-for-split
            - feature/git-subtree-for-split-1

jobs:
    provide_packages_json:
        runs-on: ubuntu-latest
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            -   uses: eonx-com/actions-composer-install@v1

            -   id: output_data
                run: echo "::set-output name=matrix::$(bin/monorepo export-packages)"

        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    split_packages:
        needs: provide_packages_json
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                mapping: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}

        steps:
            # -   run: git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all

            -   run: git init split_dir

            -   run: |
                    cd split_dir
                    git config user.email "nathan.page@eonx.com"
                    git config user.name "natepage"
                    git commit --allow-empty -m "initial commit"

            -   run: |
                    cd split_dir
                    git remote add split https://natepage:${{ secrets.MONOREPO_GITHUB_TOKEN }}@github.com/eonx-com/${{ matrix.mapping.repo }}.git
                    git subtree add --prefix=packages/${{ matrix.mapping.dir }} --squash split ${{ steps.branch_name.outputs.branch }}
                    ls -la packages/${{ matrix.mapping.dir }}

#            -   uses: eonx-com/actions-checkout@v2
#
#
#
#            -   id: branch_name
#                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#
#            -   run: git init --bare "split_dir"
#            -   run: git subtree split --prefix=packages/${{ matrix.mapping.dir }} -b split
#            -   run: git push "split_dir" split:"${{ steps.branch_name.outputs.branch }}"
#            -   run: |
#                    cd split_dir
#                    git remote add split https://natepage:${{ secrets.MONOREPO_GITHUB_TOKEN }}@github.com/eonx-com/${{ matrix.mapping.repo }}.git
#                    git push -u split "${{ steps.branch_name.outputs.branch }}"
