name: Split Tests

on: [push, pull_request]

jobs:
    after_split_testing:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '7.3' ]
                package:
                    - EasyApiToken
                    - EasyAsync
                    - EasyCore
                    - EasyDecision
                    - EasyEntityChange
                    - EasyIdentity
                    - EasyLogging
                    - EasyPagination
                    - EasyPipeline
                    - EasyPsr7Factory
                    - EasyRepository
                    - EasySecurity
                    - EasyStandard
                    - EasyTest

        name: ${{ matrix.package }}

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php }}-comp-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ matrix.php }}-comp-

            -   run: composer global require hirak/prestissimo
            -   run: composer install --prefer-dist --no-progress
            -   run: vendor/bin/monorepo-builder localize-composer-paths
            -   run: cd packages/${{ matrix.package }}; composer update --prefer-dist --no-progress
            -   run: cd packages/${{ matrix.package }}; vendor/bin/phpunit tests
