name: Split Packages

on:
    push:
        branches:
            - master
            - 3.x

jobs:
    provide_packages_json:
        runs-on: ubuntu-latest
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            -   uses: eonx-com/actions-composer-install@v1

            -   id: output_data
                run: echo "::set-output name=matrix::$(bin/monorepo export-packages)"

        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    split_packages:
        needs: provide_packages_json
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                mapping: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}

        steps:
            -   uses: eonx-com/actions-checkout@v2
            -   run: git fetch --prune --unshallow

            -   id: previous_tag
                uses: eonx-com/github-action-get-previous-tag@master

            -   id: branch_name
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

            -   name: Split ${{ matrix.mapping.dir }}
                uses: eonx-com/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
                with:
                    branch: ${{ steps.branch_name.outputs.branch }}
                    package-directory: 'packages/${{ matrix.mapping.dir }}'
                    split-repository-organization: 'eonx-com'
                    split-repository-name: '${{ matrix.mapping.repo }}'
                    tag: ${{ steps.previous_tag.outputs.tag }}
                    user-email: 'nathan.page@eonx.com'
                    user-name: 'natepage'
