name: Split Packages

on:
    push:
        branches:
            - feature/git-subtree-for-split
            - feature/git-subtree-for-split-1

jobs:
    provide_packages_json:
        runs-on: ubuntu-latest
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            -   uses: eonx-com/actions-composer-install@v1

            -   id: output_data
                run: echo "::set-output name=matrix::$(bin/monorepo export-packages)"

        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    split_packages:
        needs: provide_packages_json
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                mapping: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}

        name: Split ${{ matrix.mapping.dir }}

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   name: Remove Git Extra Header
                run: git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all

            -   name: Resolve current branch
                id: branch_name
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

            -   name: Add Repo Remote
                run: git remote add split-remote https://natepage:${{ secrets.MONOREPO_GITHUB_TOKEN }}@github.com/eonx-com/${{ matrix.mapping.repo }}.git

            -   name: Split packages/${{ matrix.mapping.dir }}
                env:
                    BRANCH: ${{ steps.branch_name.outputs.branch }}
                    DIR: packages/${{ matrix.mapping.dir }}
                run: |
                    git checkout -b "local-$BRANCH-checkout" "$BRANCH"
                    git subtree split --prefix="packages/${{ matrix.mapping.dir }}" --branch="local-$BRANCH" "$BRANCH"
                    git push --force split-remote local-$BRANCH:$BRANCH

    release_tag:
        needs:
            - provide_packages_json
            - split_packages
        if: contains(github.event.head_commit.message, '[Release]')
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                tag: [ '3.0.11-alpha1' ]
                mapping: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}

        env:
            DIR: packages/${{ matrix.mapping.dir }}
            TAG: ${{ matrix.tag }}

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   name: Remove Git Extra Header
                run: git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all

            -   name: Release eonx-com/${{ matrix.mapping.repo }}:${{ matrix.tag }}
                shell: bash
                run: |
                    if [ -d "$DIR" ] && [ git rev-parse "$TAG" ];
                    then
                        git checkout -b "local-$TAG-checkout" "tags/$TAG"
                        git subtree split -q --prefix="$DIR" --branch="local-$TAG" "$TAG"
                        git push -q --force origin local-$TAG:refs/tags/$TAG
                    fi
